[package]
name = "rust8_v2"
version = "0.1.0"
authors = ["Tom Jorquera <tom@jorquera.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
